### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by Virnios** [JawhnL5/Toontown-Level-Editor#17]
How do I get my  props to rotate without having to go to the hpr/xyz/scale window?

**Comment by ToontownLittleCat** [comment]
I think you can use the arrow keys to rotate and move things without adjusting them manually. If not, then I don't know, haven't used it in a long time.

**Comment by Sparkpin** [comment]
#Rotation Z Axis Functions per current Grid Snap Angle
    ('shift-control-arrow_left', self.keyboardXformSelected, ['left', 'rotate']),
    ('shift-control-arrow_right', self.keyboardXformSelected, ['right', 'rotate']),

    #Rotation Z Axis Functions per One(1) PandaUnit
    ('shift-control-arrow_up', self.keyboardXformSelected, ['up', 'rotate']),
    ('shift-control-arrow_down', self.keyboardXformSelected, ['down', 'rotate']),
