### ISSUE TITLE
Question: How do I place Suit Path/Cells

### ISSUE THREAD

**Issue by Virnios** [JawhnL5/Toontown-Level-Editor#18]
How do I place suit paths / cells cause I made a vis group but I dunno what to do after?

**Comment by vincent15k** [comment]
I've been wondering also, doesn't it have to do with pushing 'shift'?

**Comment by Virnios** [comment]
I have tried shift, control and other keys. however nothing seems to work.

**Comment by vincent15k** [comment]
But now I've just resorted to putting it in the .dna code

**Comment by Sparkpin** [comment]
SHIFT+s will create a suit path point, SHIFT+C creates a suit battle cell. Make sure they are visible.

**Comment by Virnios** [comment]
Alright, thanks. Will try this out now

**Comment by Virnios** [comment]
Sparkpin, am I doing this correctly? http://prntscr.com/88vld5

**Comment by Sparkpin** [comment]
Looks good to me

**Comment by vincent15k** [comment]
Thanks @Sparkpin
