### ISSUE TITLE
Level editor hangs on windows 8

### ISSUE THREAD

**Issue by craigy109** [JawhnL5/Toontown-Level-Editor#5]
Hello i am using a nividia gtx980 graphics card on windows 8.1 i get the following error i do not know if it is something wrong with the setup or what. But here is the info i get, I can not get past the command prompt as the window does not load it just hangs after the following.

DirectStart: Starting the game.
Known pipe types:
  wdxGraphicsPipe9
  wdxGraphicsPipe8
  wglGraphicsPipe
(all display modules loaded.)
:display:windisplay: OS version: 6.2.2.9200
:display:windisplay:
:display:windisplay: max Mhz 4001000000, current Mhz 4001000000
:display:wdxdisplay9: DX 9.0c GetAvailableVidMem (including AGP) returns Total:
4294901760, Free: 4286607360 for device #0
:display:wdxdisplay9: GetAvailableVidMem (no AGP) returns Total: 3221225472, Fre
e: 3212931072 for device #0

**Comment by craigy109** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1594178/8255512/56673a54-1698-11e5-8bc9-562832e611da.jpg)

**Comment by ToontownLittleCat** [comment]
I am also using Windows 8.1, and I can run it just fine for me.

**Comment by DenialMC** [comment]
I had the same issue, all I had to do was import libpandagl instead of dx.

**Comment by JawhnL5** [comment]
I believe I fixed this by prioritizing OpenGL by default. Let me know if it works. https://github.com/JawhnL5/Toontown-Level-Editor/commit/29b97b3a1469cd7fa7697e6a07d377cb2fa44874

**Comment by craigy109** [comment]
Yes that works perfect now JawhnL5 cheers keep up the good work
