### ISSUE TITLE
Robot toon 

### ISSUE THREAD

**Issue by craigy109** [JawhnL5/Toontown-Level-Editor#9]
it seems that commit 8147478a2978b6a7f708e8c215cba5e35b0f7518
has caused drive mode to crash, this is the error that gets sent regarding robot toon
http://pastebin.com/JacgdfQQ
Hope this is useful to you guys

**Comment by loganotoon** [comment]
Prior to the commit, this issue still occurred randomly. It wasn't the commit that broke it.

**Comment by craigy109** [comment]
Okay loganotoon didnt notice it i can use previous versions with drive mode without a problem only when i use latest commit does the errors occur for me

**Comment by sean5470** [comment]
I see a lot of these entries in your paste:
":loader: Reading ./phase_3.5/models/char/tt_a_chr_dgm_shorts_legs_teleport.bam
:util:bam(error): Bam file is version 6.30.
:util:bam(error): This program can only load version 6.14 through 6.24 bams."
are the model files your using in those instances incompatible by chance? Meaning, from a more current phase set?

**Comment by Sparkpin** [comment]
[You require the Toontown Online phase files.](https://dl.dropboxusercontent.com/u/47018135/Toontown/ToonTown_Files/US_Open_Phase_Files/ToontownOnline_Full_Directory.zip)

**Comment by sean5470** [comment]
LOL  those are from my dropbox.  :P   I have a link to an extracted set instead.  
https://dl.dropboxusercontent.com/u/47018135/Toontown/ToonTown_Files/US_Open_Phase_Files/PhaseFiles_Extracted.zip

**Comment by craigy109** [comment]
thanks for these guys what files do you recommend using in terms of source codes to test out the edits like tt offline tti/ ttf? or?

**Comment by sean5470** [comment]
eh, it could be any really. Though IK with TTI, you'd have to compile any DNA you've created into its pdna equivalent prior to it working with the source.

**Comment by Sparkpin** [comment]
@sean5470 Rewritten's, so we use XMLs... but not for long.

TTOff Squirting Flower/Bike Horn, however, used straight .dna files, which makes for easy easy testing.
